/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardLayoutImport } from './routes/dashboard/layout'
import { Route as IndexImport } from './routes/index'
import { Route as SettingsIndexImport } from './routes/settings/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as SettingsAiImport } from './routes/settings/ai'
import { Route as NoteNoteIdImport } from './routes/note/$noteId'
import { Route as OnboardingIndexImport } from './routes/onboarding/index'
import { Route as AiChatImport } from './routes/ai/chat'

// Create/Update Routes

const DashboardLayoutRoute = DashboardLayoutImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute
} as any)

const OnboardingIndexRoute = OnboardingIndexImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRoute
} as any)

const SettingsIndexRoute = SettingsIndexImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRoute
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute
} as any)

const SettingsAiRoute = SettingsAiImport.update({
  id: '/settings/ai',
  path: '/settings/ai',
  getParentRoute: () => rootRoute
} as any)

const NoteNoteIdRoute = NoteNoteIdImport.update({
  id: '/note/$noteId',
  path: '/note/$noteId',
  getParentRoute: () => rootRoute
} as any)

const AiChatRoute = AiChatImport.update({
  id: '/ai/chat',
  path: '/ai/chat',
  getParentRoute: () => rootRoute
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutImport
      parentRoute: typeof rootRoute
    }
    '/ai/chat': {
      id: '/ai/chat'
      path: '/ai/chat'
      fullPath: '/ai/chat'
      preLoaderRoute: typeof AiChatImport
      parentRoute: typeof rootRoute
    }
    '/note/$noteId': {
      id: '/note/$noteId'
      path: '/note/$noteId'
      fullPath: '/note/$noteId'
      preLoaderRoute: typeof NoteNoteIdImport
      parentRoute: typeof rootRoute
    }
    '/settings/ai': {
      id: '/settings/ai'
      path: '/settings/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof SettingsAiImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingIndexImport
      parentRoute: typeof rootRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface DashboardLayoutRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/ai/chat': typeof AiChatRoute
  '/note/$noteId': typeof NoteNoteIdRoute
  '/settings/ai': typeof SettingsAiRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/settings': typeof SettingsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai/chat': typeof AiChatRoute
  '/note/$noteId': typeof NoteNoteIdRoute
  '/settings/ai': typeof SettingsAiRoute
  '/dashboard': typeof DashboardIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/settings': typeof SettingsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/ai/chat': typeof AiChatRoute
  '/note/$noteId': typeof NoteNoteIdRoute
  '/settings/ai': typeof SettingsAiRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/settings/': typeof SettingsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/ai/chat'
    | '/note/$noteId'
    | '/settings/ai'
    | '/dashboard/'
    | '/onboarding'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ai/chat' | '/note/$noteId' | '/settings/ai' | '/dashboard' | '/onboarding' | '/settings'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/ai/chat'
    | '/note/$noteId'
    | '/settings/ai'
    | '/dashboard/'
    | '/onboarding/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  AiChatRoute: typeof AiChatRoute
  NoteNoteIdRoute: typeof NoteNoteIdRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  SettingsAiRoute: typeof SettingsAiRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  AiChatRoute: AiChatRoute,
  NoteNoteIdRoute: NoteNoteIdRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  SettingsAiRoute: SettingsAiRoute,
  SettingsIndexRoute: SettingsIndexRoute
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/ai/chat",
        "/note/$noteId",
        "/onboarding/",
        "/settings/ai",
        "/settings/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard/layout.tsx",
      "children": [
        "/dashboard/"
      ]
    },
    "/ai/chat": {
      "filePath": "ai/chat.tsx"
    },
    "/note/$noteId": {
      "filePath": "note/$noteId.tsx"
    },
    "/settings/ai": {
      "filePath": "settings/ai.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    },
    "/onboarding/": {
      "filePath": "onboarding/index.tsx"
    },
    "/settings/": {
      "filePath": "settings/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
